export const API = 'API';
export const API_START = 'API_START';
export const API_END = 'API_END';
export const ACCESS_DENIED = 'ACCESS_DENIED';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const API_ERROR = 'API_ERROR';

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_ERROR = 'SET_CURRENT_USER_ERROR';
export const RESET_CURRENT_USER = 'RESET_CURRENT_USER';

export const FETCH_TWITTER_REQUEST_TOKEN = 'FETCH_TWITTER_REQUEST_TOKEN';
export const SET_TWITTER_REQUEST_TOKEN = 'SET_TWITTER_REQUEST_TOKEN';
export const SET_TWITTER_REQUEST_TOKEN_ERROR = 'SET_TWITTER_REQUEST_TOKEN_ERROR';

export const FETCH_TWITTER_AUTH = 'FETCH_TWITTER_AUTH';
export const SET_TWITTER_AUTH = 'SET_TWITTER_AUTH';
export const SET_TWITTER_AUTH_ERROR = 'SET_TWITTER_AUTH_ERROR';

export const FETCH_TWEETS = 'FETCH_TWEETS';
export const SET_TWEETS = 'SET_TWEETS';
export const SET_TWEETS_ERROR = 'SET_TWEETS_ERROR';

export const FETCH_SEARCH_TWEETS = 'FETCH_SEARCH_TWEETS';
export const SET_SEARCH_TWEETS = 'SET_SEARCH_TWEETS';
export const SET_SEARCH_TWEETS_ERROR = 'SET_SEARCH_TWEETS_ERROR';

export const FETCH_STATS = 'FETCH_STATS';
export const SET_STATS = 'SET_STATS';
export const SET_STATS_ERROR = 'SET_STATS_ERROR';
